### ISSUE TITLE
Pack float to RGBA

### ISSUE THREAD

**Issue by Herjar** [ihmeuw/glsl-rgba-to-float#1]
Thanks for the package. It works great to get float data into a shader. I do calculations in the shader and would like to return some float data. Is it possible to extend this package to support packing floats back to RGBA, or do you have a suggestions how else I could do that?

**Comment by davschne** [comment]
Hi!  Glad you’ve found this package useful!

As regards converting floats to RGBA, have you looked at this package?

https://github.com/mikolalysenko/glsl-read-float

**Comment by Herjar** [comment]
That package does exactly what I want. Thank you!
